// Optional rendered QA. Requires a permitted Playwright/Chromium environment.
// This task's cloud sandbox previously blocked Chromium sockets: do not retry here.
const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname;const file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{const content=fs.readFileSync(file);res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.json')?'application/json':'text/html');res.end(content);}catch{res.writeHead(404).end();}});
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));let browser;
 try{
  browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>document.querySelectorAll('.experience-card').length===17);
  assert.equal(await page.locator('#panel-start').isVisible(),true);await page.locator('[data-intent=writing]').click();assert.equal(await page.locator('#skill-filter').inputValue(),'writing');assert.equal(await page.locator('#site-intro').isVisible(),false);assert.equal(await page.locator('#advanced-filters').getAttribute('open'),null);assert.match(await page.locator('#learning-guide').innerText(),/初稿/);
  await page.locator('.method-detail > summary').click();assert.equal(await page.locator('.method-detail .detail-body').isVisible(),true);
  await page.locator('#skill-navigation [data-skill=all]').click();assert.equal(await page.locator('.resource-card').count(),21);await page.locator('#advanced-filters > summary').click();await page.selectOption('#recommendation-filter','reference');assert.equal(await page.locator('.resource-card').count(),12);
  const reddit=page.locator('[data-resource-id="reddit-writing-feedback-compare-2026"]');await reddit.locator('summary').click();assert.match(await reddit.innerText(),/与原帖发帖人不同/);await reddit.locator('[data-save]').click();assert.equal(await reddit.locator('details').getAttribute('open'),'');await page.locator('#saved-filter').click();assert.equal(await page.locator('.resource-card').count(),1);await reddit.locator('[data-save]').click();assert.equal(await page.locator('.resource-card').count(),0);assert.equal(await page.locator('#saved-filter').evaluate(n=>n===document.activeElement),true);
  await page.locator('#tab-experience').click();assert.equal(await page.locator('.experience-card').count(),17);assert.equal(await page.locator('#experience-scope').inputValue(),'all');await page.selectOption('#experience-scope','recommended');assert.equal(await page.locator('.experience-card').count(),6);await page.selectOption('#experience-scope','reference');assert.equal(await page.locator('.experience-card').count(),11);await page.selectOption('#experience-scope','all');assert.equal(await page.locator('.experience-card').count(),17);await page.selectOption('#experience-topic','timing');assert.equal(await page.locator('.experience-card').count(),9);await page.locator('.experience-card').first().locator('summary').click();assert.match(await page.locator('.experience-card').first().innerText(),/核读边界/);
  await page.locator('#tab-path').click();await page.selectOption('#exam-history','no');await page.locator('#plan-next').click();await page.selectOption('#target','7');await page.locator('#plan-next').click();await page.selectOption('#daily-time','60');await page.locator('#plan-next').click();await page.goBack();assert.equal(await page.locator('#plan-step-3').isVisible(),true);assert.equal(await page.locator('#daily-time').inputValue(),'60');await page.goForward();await page.selectOption('#weak-skill','writing');await page.locator('#plan-next').click();assert.equal(await page.locator('.today-task').count(),3);assert.equal(await page.locator('.week-day').count(),7);assert.match(await page.locator('#path-result').innerText(),/每天约 60 分钟/);await page.locator('.today-task').nth(1).getByText('打开资料摘要',{exact:true}).click();assert.equal(await page.locator('#detail-writing-rubric').getAttribute('open'),'');await page.goBack();assert.equal(await page.locator('#path-result').isVisible(),true);await page.reload();assert.equal(await page.locator('#path-result').isVisible(),true);await page.locator('#edit-plan').click();assert.equal(await page.locator('#plan-step-1').isVisible(),true);
  await page.locator('#tab-exams').click();assert.equal(await page.locator('.center-card').count(),4);assert.equal(await page.locator('.policy-card').count(),3);assert.match(await page.locator('#exam-overview').innerText(),/尚无逐日核验/);assert.ok((await page.locator('#center-list').boundingBox()).y<(await page.locator('#policy-grid').boundingBox()).y);assert.match(await page.locator('#update-status').innerText(),/首轮待验证/);
  for(const width of [1440,390]){await page.setViewportSize({width,height:width===390?844:1000});for(const tab of ['library','experience','path','exams']){await page.locator('#tab-'+tab).click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,tab+' no horizontal overflow at '+width);await page.screenshot({path:path.join(root,'review/guided-'+tab+'-'+width+'.png'),fullPage:true});}}
  assert.deepEqual(errors,[]);console.log('PASS rendered guided pages: summary/detail/source, experience scopes/topics, wizard back/forward/restore/action links, bookmarks, 4 centers, 3 policies, no dates invented, desktop/mobile overflow, no JS errors.');
 }finally{if(browser)await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
