const assert=require('node:assert/strict'),core=require('../assets/core.js'),experience=require('../assets/experience.js'),catalog=core.normalizeCatalog(require('../data/catalog.json'));
for(const history of ['yes','no','unknown'])for(const target of ['unknown','6.5','7','7.5'])for(const minutes of ['15','30','60','90'])for(const weak of ['unknown','listening','reading','writing','speaking']){
 const p=core.buildPlan({examHistory:history,target,dailyMinutes:minutes,weakSkill:weak});assert.equal(p.today.reduce((sum,t)=>sum+t.minutes,0),Number(minutes));assert.equal(p.days.length,7);assert.equal(new Set(p.days.map(d=>d.skill)).size,4);assert.ok(p.today.every(t=>t.minutes>0&&catalog.resources.some(r=>r.id===t.resource&&r.recommendedByDefault!==false)));assert.ok(p.note.includes('不预测分数'));assert.ok(p.note.includes('首考日期'));
}
for(const [skill,guide] of Object.entries(core.learningGuides)){assert.equal(guide.steps.length,3);assert.ok(guide.resources.every(id=>catalog.resources.some(r=>r.id===id&&r.recommendedByDefault!==false)));assert.ok(guide.basis.includes('建议')||guide.basis.includes('编辑'));assert.equal(core.parseRoute('#library/'+skill).skill,skill);}
assert.equal(core.parseRoute('#library/writing/resource/writing-rubric').resource,'writing-rubric');assert.equal(core.parseRoute('#path/step/5').planStep,null);assert.equal(core.parseRoute('#path/step/2').planStep,2);assert.equal(core.parseRoute('#path/result').planResult,true);for(const tab of ['library','path','exams','experience'])assert.equal(core.parseRoute('#'+tab).tab,tab);
const migrated=core.readState(JSON.stringify({saved:['a'],path:{target:'7',examHistory:'yes',dailyMinutes:'60',weakSkill:'speaking',completed:true}}));assert.equal(migrated.path.dailyMinutes,'60');assert.equal(migrated.path.weakSkill,'speaking');assert.equal(migrated.path.baseline,'unknown');assert.deepEqual(core.readState('{"saved":["a"],"path":"bad"}').saved,['a']);
assert.equal(experience.selectCases(catalog.resources).length,5);assert.equal(experience.selectCases(catalog.resources,'all','reference').length,7);assert.equal(experience.selectCases(catalog.resources,'all','all').length,12);for(const topic of Object.keys(experience.topics))assert.ok(experience.selectCases(catalog.resources,topic).length>0);assert.equal(experience.selectCases(catalog.resources,'timing','all').length,5);
for(const r of catalog.resources.filter(r=>r.sourceType==='experience')){const c=experience.caseContent(r);assert.ok(c.baseline&&c.training.length&&c.outcome&&c.limit&&c.comments.length);}
console.log('PASS: 240 bounded plans, time sums, 4-skill coverage, all guidance links use recommended resources; new/legacy hashes and state; 12 experience records with 5 recommended/7 references and valid topic/content boundaries.');
