const {legacyResources}=require('./resource-history.js');
const counts=require('./catalog-counts.js');
const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const raw=require('../data/catalog.json');
const core=require('../assets/core.js');
const digest=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
assert.equal(digest(legacyResources(raw.resources).slice(0,40)),'0cba66ebeeac758b10bc3cba92945c51773d04385e4d1cf3c0047e6ad195b8ab','all forty pre-refresh original fields are unchanged');
assert.equal(raw.resources.length,counts.resources);
const added=raw.resources[40];
assert.equal(added.id,'official-independent-reading-project');
assert.equal(added.sourceType,'official');
assert.equal(added.recommendedByDefault,true);
assert.equal(added.publishedAt,'2021-10-11');
assert.equal(added.checkedAt,'2026-10-02');
assert.equal(new URL(added.url).hostname,'ielts.org');
assert.ok(added.actionableMethods.some(s=>s.includes('20分钟')&&s.includes('不是官方考试限时')));
assert.ok(added.caution.includes('不保证提分'));
assert.ok(added.evidenceScope.includes('未把外链文章计作已读'));
assert.equal(added.commentsReview.status,'not_applicable');
const normalized=core.normalizeCatalog(raw);
assert.equal(normalized.resources.find(r=>r.id===added.id).access,'open','free public article remains in directly accessible filter');
assert.equal(normalized.resources.filter(r=>r.sourceType==='experience').length,counts.experiences);
assert.equal(core.filterResources(normalized.resources,{recommendation:'recommended'},[]).length,22);
assert.equal(core.filterResources(normalized.resources,{recommendation:'reference'},[]).length,counts.reference);
for(const skill of ['reading','writing','speaking'])assert.ok(core.filterResources(normalized.resources,{skill,recommendation:'recommended'},[]).some(r=>r.id===added.id));
assert.equal(raw.metadata.checkedAt,'2026-10-01','do not imply all historical sources were re-read');
assert.equal(raw.metadata.firstScheduledRunVerified,true);
assert.equal(raw.metadata.lastScheduledCheckAt,'2026-10-03');
const previousRefresh=raw.scheduledRefreshHistory.find(review=>review.checkedAt==='2026-10-02');assert.ok(previousRefresh);
assert.ok(raw.metadata.lastScheduledCheckScope.includes('未重读全部既有资源'));
assert.deepEqual(previousRefresh.newResourceIds,[added.id]);
assert.equal(previousRefresh.sourceCoverage.length,8);
assert.ok(previousRefresh.sourceCoverage.some(s=>s.platform==='抖音'&&s.scope.includes('没有观看视频')));
assert.ok(previousRefresh.sourceCoverage.some(s=>s.platform==='小红书／贴吧'&&s.scope.includes('不计入正文阅读覆盖')));
assert.deepEqual(raw.calendar.dates,[]);
assert.deepEqual(raw.calendar.centerSessions,[]);
assert.equal(raw.calendar.seatsAvailable,null);
assert.ok(raw.centers.every(c=>c.seatsAvailable===null&&c.sessions.length===0));
console.log('PASS: current catalog counts and complete experience coverage; retained source, route, state, and provenance regressions.');
